# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "radiant-banner_rotator-extension"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew vonderLuft", "Sean Cribbs"]
  s.date = "2013-01-24"
  s.description = "Allows addition and independent management of rotating banners on pages."
  s.email = "avonderluft@avlux.net"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitmodules",
    "HELP.textile",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/banners_controller.rb",
    "app/helpers/admin/banners_helper.rb",
    "app/models/banner.rb",
    "app/models/banner_placement.rb",
    "app/views/admin/banners/_form.html.haml",
    "app/views/admin/banners/_modify_banner.html.haml",
    "app/views/admin/banners/deactivate.html.haml",
    "app/views/admin/banners/edit.html.haml",
    "app/views/admin/banners/index.html.haml",
    "app/views/admin/banners/new.html.haml",
    "app/views/admin/banners/remove.html.haml",
    "app/views/admin/pages/_banner_info.html.haml",
    "app/views/admin/pages/_banners_column.html.haml",
    "app/views/admin/pages/_banners_column_header.html.haml",
    "banner_rotator_extension.rb",
    "config/initializers/radiant_config.rb",
    "config/locales/en.yml",
    "config/routes.rb",
    "db/migrate/001_create_banners.rb",
    "db/migrate/002_change_banners_default.rb",
    "db/migrate/003_add_description.rb",
    "lib/banner_rotator/page_extensions.rb",
    "lib/banner_rotator/tags.rb",
    "lib/tasks/banner_rotator_extension_tasks.rake",
    "public/images/admin/deactivate.png",
    "public/images/admin/pictures.png",
    "public/images/admin/text_list_numbers.png",
    "public/javascripts/lowpro.js",
    "radiant-banner_rotator-extension.gemspec",
    "spec/controllers/admin_banners_controller_spec.rb",
    "spec/datasets/banners_dataset.rb",
    "spec/helpers/admin/banners_helper_spec.rb",
    "spec/models/banner_placement_spec.rb",
    "spec/models/banner_spec.rb",
    "spec/models/page_extensions_spec.rb",
    "spec/models/tags_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/avonderluft/radiant-banner_rotator-extension"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Banner Rotator Extension for Radiant CMS"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 0.9.1"])
    else
      s.add_dependency(%q<radiant>, [">= 0.9.1"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 0.9.1"])
  end
end

